version: '2.1a'

networks:
  conpot_guardianast_local:

services:

# Conpot service using the Guardian AST Tank Monitoring System Template
  conpot_guardianast:
    container_name: conpot_guardianast
    restart: always
    networks:
     - conpot_guardianast_local
    ports:
     - "10001:10001"
    image: "dtagdevsec/conpot:1710"
    volumes:
     - /data/conpot_guardianast/log:/var/log/conpot_guardianast
